### PR TITLE
Implements DefaultDataSink dynamic queue

### LINKED ISSUE #163: Overflow in DefaultDataSink.enqueue (slow audio format)
I used the demo app and I got the following error:

```
E/TranscodeEngine: Unexpected error while transcoding.
    java.nio.BufferOverflowException
        at java.nio.ByteBuffer.put(ByteBuffer.java:615)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.enqueue(DefaultDataSink.java:191)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:165)
        at com.otaliastudios.transcoder.internal.utils.EosIgnoringDataSink.writeTrack(eos.kt:28)
        at com.otaliastudios.transcoder.internal.data.Writer.step(Writer.kt:52)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
        at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

may be refs #138

device: [F-02L](https://www.fmworld.net/product/phone/f-02l/spec.html)
OS: 9

### PR DESCRIPTION
**Pull request by jumperson**
may be fix #163

### CODE REVIEW

**Comment by jumperson** [comment]
@natario1 
Thank you for developing a great library.
I would appreciate it if you could review the fix.

**Comment by jsnprofessor** [comment]
@jumperson Thanks for the fix

**Comment by jsnprofessor** [comment]
@jumperson

**Comment by jsnprofessor** [comment]
@jumperson

**Comment by jsnprofessor** [comment]
@jumperson Thanks for the fix. It did fix BufferOverflowException but the resulting video has some artifacts. The first video is transcoded followed by the original.

https://user-images.githubusercontent.com/11343333/218389363-bd30ba66-047e-43bd-9675-a37f94498f9e.mp4


https://user-images.githubusercontent.com/11343333/218389378-b2e10b0b-ff49-491c-a30d-7da30e30d399.mp4

**Comment by natario1** [comment]
I will investigate #163 and possibly reopen this later. Thanks a lot for your help!

**Review by natario1 — APPROVED** [review]
Thanks!

**Pull request merged**
