### PR TITLE
Initialize mOriginUs lazily

### PR DESCRIPTION
**Pull request by jumperson**
> #138
> Library transcode video with artifacts. Link to video

I have same issue.

I checked the diffs for v0.9.1 and v0.10.0 and found that there was an issue at https://github.com/natario1/Transcoder/commit/997de452835899f04d38913571e3ce601668fa6a .

After proceeding with the verification, it seems that some terminals have side effects with `mExtractor.selectTrack(i)` and `mExtractor.unselectTrack(i)` .

Therefore, I changed the timing to set `mOriginUs` .

### CODE REVIEW

**Comment by jumperson** [comment]
@natario1 
Thank you for developing a great library.
I would appreciate it if you could review the fix.

**Review by natario1 — APPROVED** [review]

**Comment by tudormarze** [comment]
Hello @jumperson I have tried the changes from the fork and transcoding a video with the `buffer.hasRemaining` [issue](https://github.com/natario1/Transcoder/pull/158), it seems to get in an infinite loop.

In my case any video downloaded from TikTok produces that issue on an Android 12 device.

**Comment by jumperson** [comment]
Hello @tudormarze.
Can you try taking in both #158 and #167 ?
Or https://github.com/StudistCorporation/Transcoder is a branch that includes both #158 and #167, so try it.

**Comment by natario1** [comment]
I cherry-picked your commit and improved a bit on it in #200 . Thanks a lot for your investigation @jumperson , this must have been very hard to catch.

**Pull request closed without merging**
